### ISSUE TITLE
회원가입/탈퇴 api

### ISSUE THREAD

**Issue by pennya** [freshpotatoteam/DocsCare#6]
1. 클라이언트에서 얻을 수 있는 정보
- 카카오  userId(고유값) / nickname / profileImagePath / thumbnailImagePath / access token
- 네이버  userId(고유값) / nickname / profileImagePath / access token

2. 서버에서 처리 요청
- 회원가입 api    
  userId(고유값) / nickname / profileImagePath / access token

- 탈퇴 api 
   userid(고유값) 

- 로그인 api
 앱에서 SNS 로그인된 사용자에 한해서 access token을 서버로 전달 
( 앱에서 access token 만료시 refresh token을 전달 )

- 로그아웃 api
 서버에서 access token값 제거

**Comment by gaepury** [comment]
사용자가 클라이언트에서 로그인한 기록이 있으면 계속 로그인 상태로 되있어야 할텐데 token같은 값은 따로 전달받지 않나?

**Comment by pennya** [comment]
SNS 로그인만 생각하고 우리 서버의 로그인은 생각못했었네..
앱에서 access token을 보내면 서버 로그인 처리할 수 있을 것 같음.
